JWFeatherstone/bootleg-barkeep

package-lock.json, package.json, src/Components/Header/Header.tsx, src/index.tsx
- Adds JS for the Header component and its navigation links and adds some of the initial setup for React Router. 
- Finishes ticket for #1 and #10 
Looking at it now, the header wrapper might be better substituted for just a blank <> given its within a component literally called Header anyway.
=> [Feature] Header, Ingredient Links, Router

src/App.css, src/App.tsx, src/Components/Header/Header.css, src/Components/Header/Header.tsx, src/Components/Home/Home.css, src/Components/Home/Home.tsx, src/Components/RandomDrink/RandomDrink.css, src/index.css
- Adds some very basic CSS for the purposes of initial alignment and layout. 
- Refactors the header component slightly to remove an explicit "home" button and to use the logo-to-be as the return button, following some suggestions from Heather on the UI for the last project.
- Refactor for #1 
- Initial contribution for #8
=> [CSS] Initial CSS Positioning for Header and Home Page

src/App.tsx, src/Components/API/apiCalls.ts, src/Components/API/utilities.ts, src/Components/Home/Home.tsx, src/index.tsx
- Adds functionality: Added the cleaning function for randomDrink to ensure data has all desired values before it is passed through to render on the page.
- Updates JS for:  Created new folder to hold apicalls and utilities may need to updated imports after merge
- Fixes bug for: Add strictMode to index.tsx to remove errors in dev tools it is wrapped in browserRouter so it still has a hierarchy to prevent future issues. 
#7
=> Feature/create utlities.ts and establish cleaner function

src/Components/API/apiCalls.ts, src/Components/DrinkDetails/DrinkDetails.tsx
- [ x]  javascript
Adds fetch call for drink details in apiCalls file
- Updates JS for: fetch call
- #23
=> Add fetch call for drink details

src/Components/DrinkCard/DrinkCard.css, src/Components/DrinkCard/DrinkCard.tsx, src/Components/DrinkGrid/DrinkGrid.css, src/Components/DrinkGrid/DrinkGrid.tsx, src/Components/Header/Header.tsx, src/Components/RandomDrink/RandomDrink.css, src/Components/RandomDrink/RandomDrink.tsx
- Adds CSS: Very basic CSS for both the drink card and drink grid 
- Updates JS for: adding class names to make CSS more targeted/specific, and also updated route names to link header and drink grid.
- Finishes iteration or ticket for #17 #18
=> Add basic css for the drinkgrid and drink card

src/App.tsx, src/Components/DrinkGrid/DrinkGrid.tsx, src/Components/Error/Error.css, src/Components/Error/Error.tsx
- Redirects the user to an error page when one of the existing fetch statements throws an error of some type. 
- Reorganizes the switching/routing within the App component such that the header and the main element does not render when the error page is up.
- Adds some initial styling to the error page. 
- Finishes iteration or ticket for #30 #31 #29
Working on the error graphic and I'll add the cypress testing for the error handling shortly. I attempted to use a redirect within the ternary statement of App, but that didn't seem to work as it does when the error occurs in other components. As such I've used conditional rendering there and set up other components to simply redirect to the right URL and its associated components when they log an error.
TypeScript seems to expect an Error to …
=> [Feature] Error Handling and Messaging

cypress/e2e/error.cy.ts, src/Components/DrinkGrid/DrinkGrid.tsx
- Writes test to confirm that the error message is correctly being rendered in the event of one of the fetch requests returning a non-200 status code (for the random drink, drink grid, and detailed view).
- #55
=> [Testing] User Error Messaging

src/App.tsx, src/Components/DrinkDetails/DrinkDetails.tsx
- Fixes bug for: Fixes double import on App and naming update in drinkdetails 
=> Correct small import issues in the App and DetailDrink files

cypress/e2e/drinkbyalcoholtype.cy.ts, cypress/e2e/home.cy.ts, cypress/e2e/random.cy.ts, src/Components/DrinkCard/DrinkCard.css, src/Components/DrinkCard/DrinkCard.tsx, src/Components/DrinkGrid/DrinkGrid.tsx
- Fixes bug for: minor changes that were not reflected in the tests when we updated some styling/functionality.
If anything doesn't look correct let me know!
=> Add some quick fixes to testing that some minor updates broke

src/App.tsx, src/Components/API/apiCalls.ts
- Updates JS for: Updated random API so that it is async await verified that the test still passes and the cleaner function is still working. 
- #43
=> Update fetch calls to async await

cypress/e2e/drinkdetails.cy.ts
- Fixes bug for: drink-card name preferred over drink-card-nav in cypress
=> Update name of div

cypress/e2e/drinkbyalcoholtype.cy.ts
- Writes test for: the back button in the browser to make sure our navigation was working correctly
As discussed this morning I went ahead and wrote a test to make sure the back button was correctly navigating back to our home page.
=> Add testing for browsers back button

src/Components/API/utilities.ts, src/Components/DrinkCard/DrinkCard.tsx, src/Components/DrinkDetails/DrinkDetails.tsx, src/Components/Home/Home.tsx, src/Components/RandomDrink/RandomDrink.tsx, src/Types/HomeProps.ts, src/Types/RandomDrinkProps.ts
- Updates TS for: cleaner more consistent use of interfaces
just added some new files and did a little moving around and renaming to reduce redundancy and also cleaned up a little blank space.
=> Add new interface files for cleaner more consistant look

src/App.css, src/Components/DrinkCard/DrinkCard.css, src/Components/DrinkGrid/DrinkGrid.css, src/Components/DrinkGrid/DrinkGrid.tsx, src/Components/Header/Header.css, src/Components/Header/Header.tsx
- Just quickly resolves some of the alignment issues so that our header and grid are flush and changes the color of the Nav elements.
=> [CSS] Alignment Fixes

src/App.css, src/Components/DrinkDetails/DrinkDetails.css, src/Components/DrinkDetails/DrinkDetails.tsx
- Adds some basic CSS styling to the drink details view.
- Finishes iteration or ticket for #63 
- I'll experiment with adding some collapsible elements to the longer text sections under ingredients and instructions later and see if I can polish this up a little. At the moment, the balance of the page seems a little off and the section on the right could probably be a little more cohesive with the rest of the site.
=> [CSS] Drink Details

src/Components/DrinkDetails/DrinkDetails.tsx
- [x ]  refactor
- Updates JS for: moved the method to filter and organize ingredients and amounts out of the render method
=> move method out of render

cypress/e2e/drinkgridgin.cy.ts, cypress/e2e/drinkgridvodka.cy.ts, cypress/fixtures/gin.json, cypress/fixtures/vodka.json
- Writes test for: Added additional testing ensuring that two of our nav links work correctly and that we have tested the detailed view of the first and last click on both. 
=> Add addtional testing ensure that user can navigate multiple links

README.md
- Adds an initial project abstract and background, technologies and collaborators lists, and set up instructions. Leaves framework for the addition of the deployed project link and group reflections.
N/A
=> [DOCS] Base README Framework

src/Components/DrinkDetails/DrinkDetails.tsx, src/Types/Details.ts
- [x ]  refactor
- Updates JS for: makes typescript in DrinkDetails more specific
=> Make typescript in DrinkDetails more specific

README.md
- Add updated readme, my section of the wins and challenges and new table of contents formatting
Old version is still commented out just in case I missed transferring something over.
=> Add updated readme
